# Generated by Django 4.2.11 on 2024-05-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prefecture', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('rating', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('weighted_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
