# Generated by Django 4.2.11 on 2024-06-16 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhmilove_app', '0002_monthlydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='registered_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
    ]
