# Generated by Django 4.2.11 on 2024-06-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhmilove_app', '0003_store_registered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='registered_month',
            field=models.CharField(default='2024-01', max_length=7),
        ),
    ]
