# Generated by Django 4.2.11 on 2024-06-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhmilove_app', '0004_store_registered_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='prefecture_en',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
