# Generated by Django 4.2.11 on 2024-06-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhmilove_app', '0005_store_prefecture_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydata',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
