# Generated by Django 4.2.11 on 2024-09-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhmilove_app', '0006_alter_monthlydata_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydata',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlydata',
            name='prefecture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
