# Generated by Django 4.2.11 on 2024-09-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banhmilove_app', '0007_monthlydata_count_monthlydata_prefecture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlydata',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='NewStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateField()),
                ('month', models.CharField(max_length=7)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banhmilove_app.store')),
            ],
            options={
                'unique_together': {('registered_date', 'store')},
            },
        ),
    ]
