# Generated by Django 4.2.11 on 2024-09-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhmilove_app', '0008_alter_monthlydata_unique_together_newstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='query_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
