# Generated by Django 4.2.11 on 2024-09-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banhmilove_app', '0010_store_category_store_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('weighted_score', models.FloatField(blank=True, null=True)),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrefectureCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
        migrations.RemoveField(
            model_name='store',
            name='description',
        ),
        migrations.RemoveField(
            model_name='store',
            name='query_used',
        ),
        migrations.RemoveField(
            model_name='store',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='store',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='store',
            name='weighted_score',
        ),
        migrations.DeleteModel(
            name='MonthlyData',
        ),
        migrations.AddField(
            model_name='monthlystoredata',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banhmilove_app.store'),
        ),
    ]
