# Generated by Django 5.2.1 on 2026-05-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('body', models.TextField()),
                ('lang', models.CharField(choices=[('ja', '日本語'), ('en', 'English')], default='ja', max_length=2)),
                ('status', models.CharField(choices=[('draft', '下書き'), ('published', '公開')], default='draft', max_length=20)),
                ('meta_description', models.CharField(blank=True, default='', max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'lang', '-published_at'], name='content_pos_status_3b594b_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'lang'), name='uniq_post_slug_lang')],
            },
        ),
    ]
