# Generated by Django 5.2.1 on 2026-05-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighted_score', models.FloatField(default=0.0)),
                ('fetched_at', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.venue')),
            ],
            options={
                'indexes': [models.Index(fields=['region', 'category', '-weighted_score'], name='catalog_lis_region__ba210b_idx'), models.Index(fields=['fetched_at'], name='catalog_lis_fetched_f61971_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'category', 'venue'), name='uniq_listing_region_category_venue')],
            },
        ),
    ]
