# Generated by Django 5.2.1 on 2026-05-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('prefecture', '都道府県'), ('designated_city', '政令指定都市'), ('city', '市区町村'), ('ward', '区'), ('major_area', '主要エリア')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_major_focus', models.BooleanField(default=False, help_text='人口上位都道府県など、主要エリア展開対象の地域フラグ')),
                ('search_keywords', models.JSONField(blank=True, default=list, help_text='Places API 検索補助キーワード')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.region')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['level', 'is_active'], name='core_region_level_9031a9_idx'), models.Index(fields=['parent', 'sort_order'], name='core_region_parent__cdfc8b_idx')],
            },
        ),
    ]
