# Generated by Django 5.2.1 on 2026-05-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='center_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='center_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='radius_m',
            field=models.PositiveIntegerField(blank=True, help_text='Places検索半径（メートル）。未設定の場合は上位地域の設定を利用できるようにする想定。', null=True),
        ),
    ]
